const express = require('express');
const router = express.Router();
const authService = require('../services/auth.service');
const { validateRegistration, validateLogin } = require('../middleware/validation.middleware');
const { loginLimiter, registrationLimiter } = require('../middleware/rate-limit.middleware');
const { csrfProtection } = require('../middleware/csrf.middleware');

/**
 * POST /api/auth/register
 * Register a new user
 */
router.post('/register', registrationLimiter, validateRegistration, async (req, res) => {
  try {
    const { name, email, password } = req.body;

    // Register user
    const user = await authService.registerUser(name, email, password);

    res.status(201).json({
      success: true,
      message: 'Registration successful. Please log in.',
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role
      }
    });
  } catch (error) {
    console.error('Registration error:', error.message);
    
    // Check for duplicate email error
    if (error.message.includes('already registered')) {
      return res.status(409).json({
        success: false,
        message: 'Email already registered. Please use a different email or log in.'
      });
    }

    res.status(500).json({
      success: false,
      message: 'Registration failed. Please try again.'
    });
  }
});

/**
 * POST /api/auth/login
 * Authenticate user and create session
 */
router.post('/login', loginLimiter, validateLogin, async (req, res) => {
  try {
    const { email, password } = req.body;

    // Authenticate user
    const user = await authService.loginUser(email, password);

    // Create session
    req.session.user = {
      id: user.id,
      name: user.name,
      email: user.email,
      role: user.role
    };

    res.json({
      success: true,
      message: 'Login successful',
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role
      }
    });
  } catch (error) {
    console.error('Login error:', error.message);
    
    // Generic error message to prevent user enumeration
    res.status(401).json({
      success: false,
      message: 'Invalid email or password'
    });
  }
});

/**
 * POST /api/auth/logout
 * Destroy user session
 */
router.post('/logout', (req, res) => {
  if (req.session) {
    req.session.destroy((err) => {
      if (err) {
        console.error('Logout error:', err);
        return res.status(500).json({
          success: false,
          message: 'Logout failed. Please try again.'
        });
      }

      res.clearCookie('connect.sid'); // Clear session cookie
      res.json({
        success: true,
        message: 'Logged out successfully'
      });
    });
  } else {
    res.json({
      success: true,
      message: 'Already logged out'
    });
  }
});

/**
 * GET /api/auth/session
 * Check if user is authenticated and return session info
 */
router.get('/session', (req, res) => {
  if (req.session && req.session.user) {
    res.json({
      authenticated: true,
      user: {
        id: req.session.user.id,
        name: req.session.user.name,
        email: req.session.user.email,
        role: req.session.user.role
      }
    });
  } else {
    res.status(401).json({
      authenticated: false,
      message: 'Not authenticated'
    });
  }
});

/**
 * GET /api/auth/csrf-token
 * Get CSRF token for client-side requests
 */
router.get('/csrf-token', (req, res) => {
  // Token is already generated by csrfTokenGenerator middleware
  // and available in res.locals.csrfToken
  const token = res.locals.csrfToken;
  
  if (!token) {
    console.error('CSRF token not found in res.locals');
    return res.status(500).json({
      success: false,
      message: 'Failed to generate CSRF token'
    });
  }
  
  res.json({
    success: true,
    csrfToken: token
  });
});

module.exports = router;
